"""Small deterministic vendor trees for native staging assertions."""

from __future__ import annotations

import hashlib
from pathlib import Path


def native_build_fixture(tmp_path: Path) -> Path:
    """Create ordinary inputs, regenerable outputs, and unrelated stale files."""

    source = tmp_path / "vendor" / "pyboy-src"
    files = {
        "POKERED_HARNESS_PYBOY_REVISION": b"pinned-revision\n",
        "setup.py": b"from setuptools import setup\n",
        "pyproject.toml": b"[build-system]\nrequires = []\n",
        "README.md": b"packaging readme\n",
        "pyboy/__init__.py": b"__version__ = '2.7.0'\n",
        "pyboy/core/mb.py": b"class Motherboard: pass\n",
        "pyboy/core/mb.pxd": b"cdef class Motherboard: pass\n",
        "pyboy/core/cpu.py": b"class CPU: pass\n",
        "pyboy/core/opcodes.py": b"import cython\n",
        "pyboy/core/opcodes.pxd": b"from pyboy.core.mb cimport Motherboard\n",
        "pyboy/core/shared.pxi": b"DEF SHARED = 1\n",
        "pyboy/core/bootrom_dmg.bin": b"\x00\x80\xff",
        "pyboy/plugins/font.txt": b"builtin font\n",
        "pyboy/default_rom.gb": b"authored builtin ROM\n",
        "pyboy/core/opcodes.c": b"/* Generated by Cython 3.0.12 */\nold ABI\n",
        "pyboy/core/mb.cpp": b"/* Generated by Cython 3.0.12 */\n",
        "pyboy/core/mb.h": b"/* Generated by Cython 3.0.12 */\n",
        "pyboy/core/mb_api.h": b"/* Generated by Cython 3.0.12 */\n",
        "pyboy/core/original.c": b"/* Original C source. */\n",
        "pyboy/core/original.cpp": b"// Original C++ source.\n",
        "pyboy/core/original.h": b"/* Original header. */\n",
        "pyboy/core/original.hpp": b"// Original C++ header.\n",
        "pyboy/core/opcodes.cpython-312-x86_64-linux-gnu.so": b"stale extension\n",
    }
    for relative, content in files.items():
        path = source / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
    stale = source / "build" / "lib" / "pyboy" / "core" / "mb.py"
    stale.parent.mkdir(parents=True)
    stale.write_text("stale build copy\n", encoding="utf-8")
    metadata = source / "pyboy.egg-info" / "SOURCES.txt"
    metadata.parent.mkdir(parents=True)
    metadata.write_text("stale manifest\n", encoding="utf-8")
    return source


def source_fingerprint(source: Path) -> dict[str, tuple[str, int]]:
    """Record fixture file bytes and mtimes without reading symlink targets."""

    result = {}
    for path in source.rglob("*"):
        if path.is_symlink() or not path.is_file():
            continue
        result[path.relative_to(source).as_posix()] = (
            hashlib.sha256(path.read_bytes()).hexdigest(),
            path.stat().st_mtime_ns,
        )
    return result
