"""The link-cable tool dispatcher.

Split from ``pokered_harness.mcp_server`` for issue #125 with no behavior
change: the code below is copied verbatim except that calls to facade-owned,
monkeypatch-patched entry points resolve through ``_entry`` so attribute patches
on ``pokered_harness.mcp_server`` stay visible.
"""

from __future__ import annotations

import threading
import time
from typing import Any

from pokered_harness.link.network_backend import NetworkBackendError
from pokered_harness.link.serial_link import SerialLinkError

# Direct names this module calls; cyclic back-edges go through _entry.
from pokered_harness.mcp_server_model import (
    _DEFAULT_REMOTE_HELLO_TIMEOUT_S,
    _MAX_BUTTON_DURATION,
    _MAX_STEP_TICKS,
    LinkState,
    McpHarnessError,
    _bounded_positive_int,
    _error_code,
    _ListenerCancelled,
    _require_pair,
    _require_peer,
)
from pokered_harness.session import Session, locked_sessions


def _dispatch_link_tool(
    session: Session,
    name: str,
    arguments: dict[str, Any],
    link: LinkState,
) -> Any:
    if name == "link_pair":
        peer = _require_peer(link)
        with link.state():
            _entry._require_remote_idle_locked(link)
            if link._local_pair_in_progress or link._pending_local_link_session is not None:
                raise McpHarnessError(
                    "link_busy",
                    "local setup cleanup is pending; call link_disconnect "
                    "before starting another pair",
                )
            if link.pair is not None and link.pair.paired:
                raise McpHarnessError("already_paired", "already paired; call link_unpair first")
            if link.local_link_session is not None:
                raise McpHarnessError("already_paired", "already paired; call link_unpair first")
            pair = link.pair
            created = pair is None

        # Real sessions must use the forked PyBoy serial implementation so
        # every link edge is generated by the ROM and native serial core.
        # The semantic LinkPair below remains useful for deterministic fake
        # sessions and compatibility tests, but is not a production backend.
        primary_supports_native = _entry._supports_bit_accurate_network(session)
        peer_supports_native = _entry._supports_bit_accurate_network(peer)
        if pair is None:
            _entry._require_native_network_contract(
                session,
                supported=primary_supports_native,
                role="primary",
            )
            _entry._require_native_network_contract(
                peer,
                supported=peer_supports_native,
                role="peer",
            )
        else:
            _entry._reject_semantic_pair_on_native_runtime(pair, session, peer)

        # Reserve a local setup generation only after all admission checks.
        # ``link_disconnect`` can then cancel attach/pair setup without
        # acquiring the operation lock or touching a completed local pair.
        with link.state():
            local_generation = link._local_generation + 1
            link._local_generation = local_generation
            link._local_pair_in_progress = True
            link._local_setup_done.clear()

        if pair is None and primary_supports_native and peer_supports_native:
            local_link_session: _entry.PyBoyLinkSession | None = None
            lock_deadline = time.monotonic() + _entry._DEFAULT_CLEANUP_TIMEOUT_S
            try:
                local_link_session = _entry.PyBoyLinkSession.local()
                with link.state():
                    link._pending_local_link_session = local_link_session
                    link._local_setup_deadline = lock_deadline
                # Use a stable lock order; both sessions are owned by this
                # MCP server and no callback is invoked while attaching.
                with (
                    locked_sessions(
                        session,
                        peer,
                        timeout_s=_entry._remaining(lock_deadline),
                    ),
                    link._pair_lock,
                ):
                    local_link_session.attach(session._pyboy)
                    local_link_session.attach(peer._pyboy)
                    if link._local_generation != local_generation:
                        raise McpHarnessError("link_cancelled", "local link pairing cancelled")
            except Exception as exc:
                cleanup_errors: list[Exception] = []
                if local_link_session is not None:
                    try:
                        _entry._detach_local_link_session(
                            link,
                            session,
                            local_link_session,
                            timeout_s=_entry._remaining(lock_deadline),
                        )
                    except Exception as cleanup_error:  # noqa: BLE001
                        cleanup_errors.append(cleanup_error)
                        # Preserve the attach failure; a later unpair/close
                        # can retry if restoration itself was interrupted.
                        exc.add_note(f"local attach cleanup failed: {cleanup_error!r}")
                try:
                    hook_errors = _entry._deactivate_link_hooks(
                        session,
                        peer,
                        timeout_s=_entry._remaining(lock_deadline),
                    )
                    cleanup_errors.extend(hook_errors)
                except Exception as cleanup_error:  # noqa: BLE001
                    cleanup_errors.append(cleanup_error)
                    exc.add_note(f"local hook cleanup failed: {cleanup_error!r}")
                if cleanup_errors:
                    with link.state():
                        # Keep ownership visible when restoration failed; the
                        # provider remains inspectable for a bounded retry.
                        link._pending_local_link_session = local_link_session
                        link._local_pair_in_progress = False
                        link._local_setup_deadline = None
                else:
                    with link.state():
                        if link._pending_local_link_session is local_link_session:
                            link._pending_local_link_session = None
                        if link._local_pair_in_progress:
                            link._local_pair_in_progress = False
                        if link._local_setup_deadline == lock_deadline:
                            link._local_setup_deadline = None
                link._local_setup_done.set()
                raise
            assert local_link_session is not None
            with link.state():
                if link._local_generation != local_generation:
                    cancelled = True
                else:
                    cancelled = False
                    link.local_link_session = local_link_session
                    if link._pending_local_link_session is local_link_session:
                        link._pending_local_link_session = None
                    if link._local_pair_in_progress:
                        link._local_pair_in_progress = False
                    if link._local_setup_deadline == lock_deadline:
                        link._local_setup_deadline = None
                    link._local_setup_done.set()
            if cancelled:
                cleanup_errors: list[Exception] = []
                try:
                    _entry._detach_local_link_session(
                        link,
                        session,
                        local_link_session,
                        timeout_s=_entry._remaining(lock_deadline),
                    )
                except Exception as cleanup_error:  # noqa: BLE001
                    cleanup_errors.append(cleanup_error)
                finally:
                    try:
                        cleanup_errors.extend(
                            _entry._deactivate_link_hooks(
                                session,
                                peer,
                                timeout_s=_entry._remaining(lock_deadline),
                            )
                        )
                    except Exception as cleanup_error:  # noqa: BLE001
                        cleanup_errors.append(cleanup_error)
                with link.state():
                    if not cleanup_errors:
                        if link._pending_local_link_session is local_link_session:
                            link._pending_local_link_session = None
                        if link.local_link_session is local_link_session:
                            link.local_link_session = None
                        if link._local_pair_in_progress:
                            link._local_pair_in_progress = False
                        if link._local_setup_deadline == lock_deadline:
                            link._local_setup_deadline = None
                    else:
                        # Keep the provider published for a later bounded
                        # retry; disconnect must not report idle while
                        # attached cores remain.
                        link._pending_local_link_session = local_link_session
                        link._local_pair_in_progress = False
                        link._local_setup_deadline = None
                link._local_setup_done.set()
                raise McpHarnessError("link_cancelled", "local link pairing cancelled")
            return {
                "paired": True,
                "primary_version": link.primary_version,
                "peer_version": link.peer_version,
            }

        pair_deadline = time.monotonic() + _entry._DEFAULT_CLEANUP_TIMEOUT_S
        try:
            if pair is None:
                pair = _entry.LinkPair(
                    session,
                    peer,
                    version_primary=link.primary_version,
                    version_peer=link.peer_version,
                )
                with link.state():
                    link.pair = pair
            with (
                locked_sessions(
                    session,
                    peer,
                    timeout_s=_entry._remaining(pair_deadline),
                ),
                link._pair_lock,
            ):
                assert pair is not None
                pair.pair()
                if link._local_generation != local_generation:
                    raise McpHarnessError("link_cancelled", "local link pairing cancelled")
            # Lock release can run integration callbacks or admit a racing
            # disconnect. Publish completion atomically with the final token
            # check, just as the native provider path does above.
            with link.state():
                if link._local_generation != local_generation:
                    raise McpHarnessError("link_cancelled", "local link pairing cancelled")
                link._local_pair_in_progress = False
        except Exception as exc:
            try:
                if pair is not None and pair.paired:
                    with (
                        locked_sessions(
                            session,
                            peer,
                            allow_closed=True,
                            timeout_s=_entry._remaining(pair_deadline),
                        ),
                        link._pair_lock,
                    ):
                        pair.unpair()
            except Exception as cleanup_error:  # noqa: BLE001
                # Preserve the operation/cancellation error. The normal
                # unpair path remains available for a later retry.
                exc.add_note(f"local pair rollback failed: {cleanup_error!r}")
            if created:
                with link.state():
                    if pair is not None and link.pair is pair:
                        link.pair = None
            _entry._deactivate_link_hooks(
                session,
                peer,
                timeout_s=_entry._remaining(pair_deadline),
            )
            raise
        finally:
            with link.state():
                if link._local_pair_in_progress:
                    link._local_pair_in_progress = False
        return {
            "paired": True,
            "primary_version": link.primary_version,
            "peer_version": link.peer_version,
        }

    if name == "link_unpair":
        with link.state():
            if link._local_pair_in_progress:
                raise McpHarnessError(
                    "link_busy", "local setup is still unwinding; retry cleanup after it finishes"
                )
            pair = link.pair
            local_link_session = link.local_link_session or link._pending_local_link_session
        cleanup_errors: list[Exception] = []
        cleanup_deadline = time.monotonic() + _entry._DEFAULT_CLEANUP_TIMEOUT_S
        if local_link_session is not None:
            try:
                _entry._detach_local_link_session(
                    link,
                    session,
                    local_link_session,
                    timeout_s=_entry._remaining(cleanup_deadline),
                )
            except Exception as exc:  # noqa: BLE001
                cleanup_errors.append(exc)
            else:
                with link.state():
                    if link.local_link_session is local_link_session:
                        link.local_link_session = None
                    if link._pending_local_link_session is local_link_session:
                        link._pending_local_link_session = None
                    link._local_setup_deadline = None
                    link._local_setup_done.set()
        if pair is not None and pair.paired:
            try:
                peer = _require_peer(link)
                with (
                    locked_sessions(
                        session,
                        peer,
                        allow_closed=True,
                        timeout_s=_entry._remaining(cleanup_deadline),
                    ),
                    link._pair_lock,
                ):
                    pair.unpair()
            except Exception as exc:  # noqa: BLE001
                cleanup_errors.append(exc)
            else:
                with link.state():
                    if link.pair is pair:
                        link.pair = None
            finally:
                # Even a partially failing pair teardown must not leave raw
                # callbacks able to reach a discarded bridge.
                _entry._deactivate_link_hooks(
                    session,
                    pair.peer,
                    timeout_s=_entry._remaining(cleanup_deadline),
                )
        elif pair is not None:
            with link.state():
                if link.pair is pair:
                    link.pair = None
        if cleanup_errors:
            details = "; ".join(f"{type(exc).__name__}: {exc}" for exc in cleanup_errors)
            raise McpHarnessError("link_teardown_failed", details)
        return {"paired": False}

    if name == "link_step":
        count = _bounded_positive_int(arguments["count"], "count", _MAX_STEP_TICKS)
        # A TCP reader can observe EOF between requests. Reconcile that
        # background state before taking a snapshot so a stale endpoint is
        # never stepped after its transport has closed.
        _entry._refresh_remote_state(link, session)
        with link.state():
            network_session = link.network_session
            local_link_session = link.local_link_session
            remote_endpoint = link.remote_endpoint
            remote_mode = link.remote_mode
            remote_link = link.remote_link
            remote_error = link._remote_error
        if network_session is not None:
            session.step(count, render=bool(arguments.get("render", False)))
            return {"primary_tick": session.current_tick(), "peer_tick": None}
        if remote_endpoint is not None:
            # The semantic endpoint ticks through Session.step() but performs
            # its hardware serial tick immediately afterward. Keep that
            # memory mutation inside the same emulator lock as the frame so
            # status/resource readers and disconnect cannot observe a half
            # completed endpoint step.
            with session.locked(timeout_s=_entry._DEFAULT_CLEANUP_TIMEOUT_S):
                remote_endpoint.step(count, render=bool(arguments.get("render", False)))
            return {"primary_tick": session.current_tick(), "peer_tick": None}
        if local_link_session is not None:
            peer = _require_peer(link)
            # The interleaved path drives PyBoy directly rather than through
            # Session.step(), so retain both canonical owner locks through
            # provider work and bookkeeping.  The provider lock is acquired
            # only after those owner locks to keep one global order.
            lock_deadline = time.monotonic() + _entry._DEFAULT_CLEANUP_TIMEOUT_S
            with (
                locked_sessions(
                    session,
                    peer,
                    timeout_s=_entry._remaining(lock_deadline),
                ),
                link._pair_lock,
            ):
                local_link_session.step_interleaved(
                    count, render=bool(arguments.get("render", False))
                )
                # PyBoyLinkSession drives the underlying emulators
                # directly; keep Session-level bookkeeping aligned with
                # the same frame count.
                session.reset_tick(session.current_tick() + count)
                peer.reset_tick(peer.current_tick() + count)
                return {
                    "primary_tick": session.current_tick(),
                    "peer_tick": peer.current_tick(),
                }
        if remote_mode != "idle" or remote_link is not None or remote_error is not None:
            raise McpHarnessError(
                "remote_not_connected",
                f"remote link is not ready for stepping (mode={remote_mode!r})",
            )
        pair = _require_pair(link)
        peer = _require_peer(link)
        lock_deadline = time.monotonic() + _entry._DEFAULT_CLEANUP_TIMEOUT_S
        with (
            locked_sessions(
                session,
                peer,
                timeout_s=_entry._remaining(lock_deadline),
            ),
            link._pair_lock,
        ):
            pair.step(count, render=bool(arguments.get("render", False)))
        return {
            "primary_tick": session.current_tick(),
            "peer_tick": link.peer_session.current_tick() if link.peer_session else None,
        }

    if name == "link_peer_press":
        peer = _require_peer(link)
        duration = _bounded_positive_int(
            arguments.get("duration", 1), "duration", _MAX_BUTTON_DURATION
        )
        peer.press(arguments["button"], duration=duration)
        return {"ok": True}

    if name == "link_peer_hold":
        peer = _require_peer(link)
        peer.hold(arguments["button"])
        return {"ok": True}

    if name == "link_peer_release":
        peer = _require_peer(link)
        peer.release(arguments["button"])
        return {"ok": True}

    if name == "link_frame_barrier":
        enabled = arguments.get("enabled")
        if type(enabled) is not bool:
            raise McpHarnessError("invalid_argument", "enabled must be a boolean")
        _entry._refresh_remote_state(link, session)
        with link.state():
            network_session = link.network_session
            remote_mode = link.remote_mode
        if network_session is None or remote_mode != "connected":
            raise McpHarnessError(
                "not_connected",
                "link_frame_barrier requires a connected remote link",
            )
        with session.locked(timeout_s=_entry._DEFAULT_CLEANUP_TIMEOUT_S):
            network_session.set_network_frame_barrier(enabled)
            applied = network_session.network_frame_barrier()
        return {
            "enabled": enabled,
            "network_frame_barrier": applied,
            "remote_mode": remote_mode,
        }

    if name == "link_status":
        # Surface listener-thread failures lazily on status checks so
        # callers polling for "connected" see the error rather than
        # hanging forever.
        _entry._refresh_remote_state(link, session)
        with link.state():
            pair = link.pair
            local_link_session = link.local_link_session
            remote_mode = link.remote_mode
            remote_role = link.remote_role
            remote_bind_port = link.remote_bind_port
            remote_link = link.remote_link
            network_session = link.network_session
            remote_error = link._remote_error or link._listener_error
        with link._pair_lock:
            paired = pair is not None and pair.paired
            paired = paired or (local_link_session is not None and local_link_session.paired)
            transport_snapshot: dict[str, Any] = (
                pair.transport.snapshot() if pair is not None else {"a_to_b": [], "b_to_a": []}
            )
        peer_rom: str | None = None
        if remote_link is not None and remote_mode == "connected":
            try:
                peer_rom = _entry._peer_rom_version_if_ready(remote_link)
            except SerialLinkError:
                peer_rom = None
        return {
            "paired": paired,
            "link_backend": (
                "bit_accurate"
                if local_link_session is not None or network_session is not None
                else ("semantic_compat" if pair is not None else None)
            ),
            "transport": transport_snapshot,
            "primary_tick": session.current_tick(),
            "peer_tick": link.peer_session.current_tick() if link.peer_session else None,
            "remote_mode": remote_mode,
            "remote_role": remote_role,
            "remote_bind_port": remote_bind_port,
            "remote_peer_rom_version": peer_rom,
            "remote_error": (
                f"{type(remote_error).__name__}: {remote_error}"
                if remote_error is not None
                else None
            ),
        }

    if name == "link_listen":
        # Validate the complete request and prove native serial capability
        # before reserving lifecycle state or binding a socket.  An
        # unsupported runtime must be observationally inert.
        port = _entry._positive_port(arguments.get("port"))
        host = _entry._validate_remote_host(str(arguments.get("host", "127.0.0.1")))
        rom_version = _entry._validate_rom_version(
            str(arguments.get("rom_version") or link.primary_version)
        )
        _entry._require_primary_rom_version(link, rom_version)
        timeout_s = _entry._validate_timeout(
            arguments.get("timeout_s", _DEFAULT_REMOTE_HELLO_TIMEOUT_S)
        )
        expected_peer_version = _entry._optional_rom_version(arguments.get("peer_rom_version"))
        cancel = threading.Event()
        start_owner = threading.get_ident()
        with link.state():
            # The idle check and reservation must be one critical section.
            # Otherwise link_disconnect can observe an apparently idle state,
            # return, and then race this call into publishing a listener it
            # never had a chance to cancel.
            _entry._require_remote_idle_locked(link)
            _entry._require_pair_inactive_locked(link)
            native_supports = _entry._supports_bit_accurate_network(session)
            _entry._require_native_network_contract(
                session,
                supported=native_supports,
                role="primary",
            )

            # Every new remote attempt gets its own generation.  A status
            # request may be finishing cleanup of an older dead transport
            # while a reconnect starts; without a new token, that status
            # request could publish the old reader error onto the new idle
            # lifecycle.
            generation = link._generation + 1
            link._generation = generation
            link._listener_cancel = cancel
            link._listener_start_in_progress = True
            link._listener_start_owner = start_owner
            link.remote_mode = "starting"
            link.remote_role = "listener"
            link.remote_bind_port = port
            link._listener_error = None
            link._remote_error = None

        try:
            try:
                listener = _entry._bind_listener(host, port)
            except Exception:
                cancel.set()
                with link.state():
                    if link._generation == generation and link.remote_mode == "starting":
                        link.remote_mode = "idle"
                        link.remote_role = None
                        link.remote_bind_port = None
                        if link._listener_cancel is cancel:
                            link._listener_cancel = threading.Event()
                raise

            def _accept() -> None:
                _entry._accept_remote(
                    link,
                    session,
                    listener,
                    cancel,
                    generation,
                    rom_version,
                    timeout_s,
                    expected_peer_version,
                )

            t = threading.Thread(target=_accept, name="mcp-link-listen", daemon=True)
            try:
                # Keep publication and start under the same lifecycle lock. If
                # disconnect races this point, it must not close the listener and
                # then leave us returning a stale "listening" state with a worker
                # that was started against a dead socket.
                with link.state():
                    if (
                        link._disconnecting
                        or link._generation != generation
                        or link.remote_mode != "starting"
                    ):
                        raise McpHarnessError("link_cancelled", "remote listener cancelled")
                    link._listener_socket = listener
                    link.remote_mode = "listening"
                    link._listener_thread = t
                    t.start()
            except Exception:
                cancel.set()
                try:
                    listener.close()
                except OSError:
                    pass
                with link.state():
                    if link._listener_socket is listener:
                        link._listener_socket = None
                    if link._listener_thread is t:
                        link._listener_thread = None
                    if link._generation == generation and not link._disconnecting:
                        link.remote_mode = "idle"
                        link.remote_role = None
                        link.remote_bind_port = None
                        if link._listener_cancel is cancel:
                            link._listener_cancel = threading.Event()
                raise
            return {
                "remote_mode": "listening",
                "remote_role": "listener",
                "remote_bind_port": port,
                "host": host,
                "rom_version": rom_version,
                "timeout_s": timeout_s,
            }
        finally:
            # A listener bind runs in the caller's thread, so it cannot be
            # joined by link_disconnect. Keep reconnects out until this call
            # has unwound and the cancelled socket has been closed.
            with link.state():
                if link._listener_start_owner == start_owner:
                    link._listener_start_in_progress = False
                    link._listener_start_owner = None

    if name == "link_connect":
        # Perform all argument and native-runtime validation before lifecycle
        # reservation, transport construction, or any socket I/O.
        host = _entry._validate_remote_host(str(arguments["host"]))
        port = _entry._positive_port(arguments.get("port"))
        rom_version = _entry._validate_rom_version(
            str(arguments.get("rom_version") or link.primary_version)
        )
        _entry._require_primary_rom_version(link, rom_version)
        timeout_s = _entry._validate_timeout(arguments.get("timeout_s", 10.0))
        expected_peer_version = _entry._optional_rom_version(arguments.get("peer_rom_version"))
        with link.state():
            # Claim the remote lifecycle before releasing the state lock so
            # a concurrent disconnect cannot miss an in-progress connect.
            _entry._require_remote_idle_locked(link)
            _entry._require_pair_inactive_locked(link)
            native_supports = _entry._supports_bit_accurate_network(session)
            _entry._require_native_network_contract(
                session,
                supported=native_supports,
                role="primary",
            )
            # Reserve a fresh token for this attempt so a racing status
            # cleanup cannot attach an older reader failure to its result.
            generation = link._generation + 1
            link._generation = generation
            link._connect_cancel = threading.Event()
            connect_cancel = link._connect_cancel
            link._connect_in_progress = True
            link._connect_done.clear()
            link.remote_mode = "connecting"
            link.remote_role = "connector"
            link.remote_bind_port = None
            link._listener_error = None
            link._remote_error = None
        transport: Any | None = None
        endpoint: _entry.RemoteLinkEndpoint | None = None
        network_session: _entry.PyBoyLinkSession | None = None
        peer_version: str | None = None
        deadline = time.monotonic() + timeout_s
        try:
            if native_supports:
                transport = _entry.NetworkBackend.connect(
                    host,
                    port,
                    timeout_s=timeout_s,
                    local_rom_version=rom_version,
                    cancel_event=connect_cancel,
                )
                _entry._track_unpublished_remote_resource(link, generation, transport=transport)
                network_session = _entry._attach_network_backend(
                    session,
                    transport,
                    is_internal_clock=False,
                    local_rom_version=rom_version,
                    network_hello_timeout_s=max(0.0, _entry._remaining(deadline)),
                )
                _entry._track_unpublished_remote_resource(
                    link, generation, network_session=network_session
                )
                peer_version = _entry._wait_for_network_hello(
                    transport,
                    connect_cancel,
                    _entry._remaining(deadline),
                    expected_peer_rom_version=expected_peer_version,
                )
                _entry._negotiate_network_clock_role(
                    session,
                    network_session,
                    peer_version,
                    timeout_s=_entry._remaining(deadline),
                )
            else:  # pragma: no cover - admission above is fail-closed
                raise McpHarnessError(
                    "unsupported_runtime",
                    "primary PyBoy lost the pinned serial contract during remote connection setup",
                )
            with link.state():
                if connect_cancel.is_set() or link._disconnecting or link._generation != generation:
                    raise McpHarnessError("link_cancelled", "remote connection cancelled")
                link.remote_link = transport
                link.remote_endpoint = endpoint
                link.network_session = network_session
                if link._pending_remote_link is transport:
                    link._pending_remote_link = None
                if link._pending_remote_endpoint is endpoint:
                    link._pending_remote_endpoint = None
                if link._pending_network_session is network_session:
                    link._pending_network_session = None
                link.remote_mode = "connected"
                link.remote_role = "connector"
                link.remote_bind_port = None
                link._remote_error = None
        except McpHarnessError:
            _entry._cleanup_unpublished_remote(
                session,
                network_session,
                transport,
                link=link,
                endpoint=endpoint,
                generation=generation,
            )
            raise
        except _ListenerCancelled as exc:
            _entry._cleanup_unpublished_remote(
                session,
                network_session,
                transport,
                link=link,
                endpoint=endpoint,
                generation=generation,
            )
            raise McpHarnessError("link_cancelled", "remote connection cancelled") from exc
        except (SerialLinkError, NetworkBackendError, OSError, TimeoutError) as exc:
            _entry._cleanup_unpublished_remote(
                session,
                network_session,
                transport,
                link=link,
                endpoint=endpoint,
                generation=generation,
            )
            if connect_cancel.is_set():
                raise McpHarnessError("link_cancelled", "remote connection cancelled") from exc
            if _error_code(exc) == "timeout":
                raise McpHarnessError("timeout", str(exc)) from exc
            raise McpHarnessError("link_connect_failed", str(exc)) from exc
        except BaseException:
            # Until state publication succeeds, this call owns every
            # transport/backend it has created.  Always release unpublished
            # resources even when an unexpected runtime or hook failure
            # escapes the protocol-specific handlers above.
            _entry._cleanup_unpublished_remote(
                session,
                network_session,
                transport,
                link=link,
                endpoint=endpoint,
                generation=generation,
            )
            raise
        finally:
            with link.state():
                if link._generation == generation and link.remote_link is None:
                    pending = (
                        link._pending_remote_link is not None
                        or link._pending_remote_endpoint is not None
                        or link._pending_network_session is not None
                    )
                    link.remote_mode = "disconnecting" if pending else "idle"
                    link.remote_role = None
                    link.remote_bind_port = None
                    if not pending:
                        link._connect_cancel = threading.Event()
                link._connect_in_progress = False
                link._connect_done.set()
        return {
            "remote_mode": "connected",
            "remote_role": "connector",
            "host": host,
            "port": port,
            "rom_version": rom_version,
            "peer_rom_version": peer_version,
        }

    if name == "link_disconnect":
        _entry._disconnect_remote(link, session)
        return {"remote_mode": "idle"}

    raise ValueError(f"unknown tool: {name!r}")


# Call-time indirection so facade-level monkeypatches stay visible here.
import pokered_harness.mcp_server as _entry
